/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellCertificateRouteImport } from './routes/_shell/certificate'
import { Route as ShellClassRouteImport } from './routes/_shell/class'
import { Route as ShellClosedRouteImport } from './routes/_shell/closed'
import { Route as ShellDataCardRouteImport } from './routes/_shell/data-card'
import { Route as ShellDeskRouteImport } from './routes/_shell/desk'
import { Route as ShellDiagnosticRouteImport } from './routes/_shell/diagnostic'
import { Route as ShellGovernanceRouteImport } from './routes/_shell/governance'
import { Route as ShellLegalRouteImport } from './routes/_shell/legal'
import { Route as ShellPracticeRouteImport } from './routes/_shell/practice'
import { Route as ShellStudioRouteImport } from './routes/_shell/studio'
import { Route as ShellWorkbookRouteImport } from './routes/_shell/workbook'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as ShellCoursesIndexRouteImport } from './routes/_shell/courses/index'
import { Route as ShellCoursesCourseIdRouteImport } from './routes/_shell/courses/$courseId'
import { Route as ShellLogIndexRouteImport } from './routes/_shell/log/index'
import { Route as ShellLogCodeRouteImport } from './routes/_shell/log/$code'
import { Route as ShellModulesIndexRouteImport } from './routes/_shell/modules/index'
import { Route as ShellModulesModuleIdRouteImport } from './routes/_shell/modules/$moduleId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCertificateRoute = ShellCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClassRoute = ShellClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClosedRoute = ShellClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDataCardRoute = ShellDataCardRouteImport.update({
  id: '/data-card',
  path: '/data-card',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDeskRoute = ShellDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDiagnosticRoute = ShellDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGovernanceRoute = ShellGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLegalRoute = ShellLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPracticeRoute = ShellPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudioRoute = ShellStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkbookRoute = ShellWorkbookRouteImport.update({
  id: '/workbook',
  path: '/workbook',
  getParentRoute: () => ShellRoute,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCoursesIndexRoute = ShellCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoursesCourseIdRoute = ShellCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogIndexRoute = ShellLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogCodeRoute = ShellLogCodeRouteImport.update({
  id: '/log/$code',
  path: '/log/$code',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModulesIndexRoute = ShellModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModulesModuleIdRoute = ShellModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => ShellRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/certificate': typeof ShellCertificateRoute
  '/class': typeof ShellClassRoute
  '/closed': typeof ShellClosedRoute
  '/data-card': typeof ShellDataCardRoute
  '/desk': typeof ShellDeskRoute
  '/diagnostic': typeof ShellDiagnosticRoute
  '/governance': typeof ShellGovernanceRoute
  '/legal': typeof ShellLegalRoute
  '/practice': typeof ShellPracticeRoute
  '/studio': typeof ShellStudioRoute
  '/workbook': typeof ShellWorkbookRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/': typeof JoinIndexRoute
  '/courses/$courseId': typeof ShellCoursesCourseIdRoute
  '/log/$code': typeof ShellLogCodeRoute
  '/modules/$moduleId': typeof ShellModulesModuleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/': typeof ShellCoursesIndexRoute
  '/log/': typeof ShellLogIndexRoute
  '/modules/': typeof ShellModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/certificate': typeof ShellCertificateRoute
  '/class': typeof ShellClassRoute
  '/closed': typeof ShellClosedRoute
  '/data-card': typeof ShellDataCardRoute
  '/desk': typeof ShellDeskRoute
  '/diagnostic': typeof ShellDiagnosticRoute
  '/governance': typeof ShellGovernanceRoute
  '/legal': typeof ShellLegalRoute
  '/practice': typeof ShellPracticeRoute
  '/studio': typeof ShellStudioRoute
  '/workbook': typeof ShellWorkbookRoute
  '/join/$code': typeof JoinCodeRoute
  '/join': typeof JoinIndexRoute
  '/courses/$courseId': typeof ShellCoursesCourseIdRoute
  '/log/$code': typeof ShellLogCodeRoute
  '/modules/$moduleId': typeof ShellModulesModuleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses': typeof ShellCoursesIndexRoute
  '/log': typeof ShellLogIndexRoute
  '/modules': typeof ShellModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/certificate': typeof ShellCertificateRoute
  '/_shell/class': typeof ShellClassRoute
  '/_shell/closed': typeof ShellClosedRoute
  '/_shell/data-card': typeof ShellDataCardRoute
  '/_shell/desk': typeof ShellDeskRoute
  '/_shell/diagnostic': typeof ShellDiagnosticRoute
  '/_shell/governance': typeof ShellGovernanceRoute
  '/_shell/legal': typeof ShellLegalRoute
  '/_shell/practice': typeof ShellPracticeRoute
  '/_shell/studio': typeof ShellStudioRoute
  '/_shell/workbook': typeof ShellWorkbookRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/': typeof JoinIndexRoute
  '/_shell/courses/$courseId': typeof ShellCoursesCourseIdRoute
  '/_shell/log/$code': typeof ShellLogCodeRoute
  '/_shell/modules/$moduleId': typeof ShellModulesModuleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_shell/courses/': typeof ShellCoursesIndexRoute
  '/_shell/log/': typeof ShellLogIndexRoute
  '/_shell/modules/': typeof ShellModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/certificate'
    | '/class'
    | '/closed'
    | '/data-card'
    | '/desk'
    | '/diagnostic'
    | '/governance'
    | '/legal'
    | '/practice'
    | '/studio'
    | '/workbook'
    | '/join/$code'
    | '/join/'
    | '/courses/$courseId'
    | '/log/$code'
    | '/modules/$moduleId'
    | '/api/auth/$'
    | '/courses/'
    | '/log/'
    | '/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/certificate'
    | '/class'
    | '/closed'
    | '/data-card'
    | '/desk'
    | '/diagnostic'
    | '/governance'
    | '/legal'
    | '/practice'
    | '/studio'
    | '/workbook'
    | '/join/$code'
    | '/join'
    | '/courses/$courseId'
    | '/log/$code'
    | '/modules/$moduleId'
    | '/api/auth/$'
    | '/courses'
    | '/log'
    | '/modules'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/certificate'
    | '/_shell/class'
    | '/_shell/closed'
    | '/_shell/data-card'
    | '/_shell/desk'
    | '/_shell/diagnostic'
    | '/_shell/governance'
    | '/_shell/legal'
    | '/_shell/practice'
    | '/_shell/studio'
    | '/_shell/workbook'
    | '/join/$code'
    | '/join/'
    | '/_shell/courses/$courseId'
    | '/_shell/log/$code'
    | '/_shell/modules/$moduleId'
    | '/api/auth/$'
    | '/_shell/courses/'
    | '/_shell/log/'
    | '/_shell/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinCodeRoute: typeof JoinCodeRoute
  JoinIndexRoute: typeof JoinIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/certificate': {
      id: '/_shell/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof ShellCertificateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/class': {
      id: '/_shell/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ShellClassRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/closed': {
      id: '/_shell/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ShellClosedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/data-card': {
      id: '/_shell/data-card'
      path: '/data-card'
      fullPath: '/data-card'
      preLoaderRoute: typeof ShellDataCardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/desk': {
      id: '/_shell/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof ShellDeskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/diagnostic': {
      id: '/_shell/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof ShellDiagnosticRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/governance': {
      id: '/_shell/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof ShellGovernanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/legal': {
      id: '/_shell/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof ShellLegalRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/practice': {
      id: '/_shell/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof ShellPracticeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/studio': {
      id: '/_shell/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof ShellStudioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workbook': {
      id: '/_shell/workbook'
      path: '/workbook'
      fullPath: '/workbook'
      preLoaderRoute: typeof ShellWorkbookRouteImport
      parentRoute: typeof ShellRoute
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/courses/': {
      id: '/_shell/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ShellCoursesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/courses/$courseId': {
      id: '/_shell/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ShellCoursesCourseIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/log/': {
      id: '/_shell/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof ShellLogIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/log/$code': {
      id: '/_shell/log/$code'
      path: '/log/$code'
      fullPath: '/log/$code'
      preLoaderRoute: typeof ShellLogCodeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/modules/': {
      id: '/_shell/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ShellModulesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/modules/$moduleId': {
      id: '/_shell/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ShellModulesModuleIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellCertificateRoute: typeof ShellCertificateRoute
  ShellClassRoute: typeof ShellClassRoute
  ShellClosedRoute: typeof ShellClosedRoute
  ShellDataCardRoute: typeof ShellDataCardRoute
  ShellDeskRoute: typeof ShellDeskRoute
  ShellDiagnosticRoute: typeof ShellDiagnosticRoute
  ShellGovernanceRoute: typeof ShellGovernanceRoute
  ShellLegalRoute: typeof ShellLegalRoute
  ShellPracticeRoute: typeof ShellPracticeRoute
  ShellStudioRoute: typeof ShellStudioRoute
  ShellWorkbookRoute: typeof ShellWorkbookRoute
  ShellCoursesCourseIdRoute: typeof ShellCoursesCourseIdRoute
  ShellLogCodeRoute: typeof ShellLogCodeRoute
  ShellModulesModuleIdRoute: typeof ShellModulesModuleIdRoute
  ShellCoursesIndexRoute: typeof ShellCoursesIndexRoute
  ShellLogIndexRoute: typeof ShellLogIndexRoute
  ShellModulesIndexRoute: typeof ShellModulesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCertificateRoute: ShellCertificateRoute,
  ShellClassRoute: ShellClassRoute,
  ShellClosedRoute: ShellClosedRoute,
  ShellDataCardRoute: ShellDataCardRoute,
  ShellDeskRoute: ShellDeskRoute,
  ShellDiagnosticRoute: ShellDiagnosticRoute,
  ShellGovernanceRoute: ShellGovernanceRoute,
  ShellLegalRoute: ShellLegalRoute,
  ShellPracticeRoute: ShellPracticeRoute,
  ShellStudioRoute: ShellStudioRoute,
  ShellWorkbookRoute: ShellWorkbookRoute,
  ShellCoursesCourseIdRoute: ShellCoursesCourseIdRoute,
  ShellLogCodeRoute: ShellLogCodeRoute,
  ShellModulesModuleIdRoute: ShellModulesModuleIdRoute,
  ShellCoursesIndexRoute: ShellCoursesIndexRoute,
  ShellLogIndexRoute: ShellLogIndexRoute,
  ShellModulesIndexRoute: ShellModulesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinCodeRoute: JoinCodeRoute,
  JoinIndexRoute: JoinIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
